# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
# Disable Dev Services for MySQL in Docker to avoid conflicts with the existing database
quarkus.datasource.devservices=false


# Hibernate ORM Configuration
quarkus.hibernate-orm.database.generation=none

# Optional: Log SQL for debugging during development
quarkus.hibernate-orm.log.sql=true

# JWT Security Configuration
mp.jwt.verify.issuer=${JWT_ISSUER}
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY}
smallrye.jwt.verify.key.location=${JWT_PUBLIC_KEY}

# Test Profile Configuration (H2 In-Memory DB)
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:vandir_test;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.database.generation=drop-and-create
