# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
# Disable Dev Services for MySQL in Docker to avoid conflicts with the existing database
quarkus.datasource.devservices.enabled=false


# Hibernate ORM Configuration
quarkus.hibernate-orm.database.update-policy=none

# Optional: Log SQL for debugging during development
quarkus.hibernate-orm.log.sql=true

# JWT Security Configuration
mp.jwt.verify.issuer=${JWT_ISSUER}
smallrye.jwt.sign.key.location=${JWT_SIGN_KEY_LOCATION}
smallrye.jwt.verify.key.location=${JWT_VERIFY_KEY_LOCATION}

# Test Profile Configuration (H2 In-Memory DB)
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:vandir_test;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.database.update-policy=drop-and-create

# CORS Configuration for Development
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.headers=${CORS_HEADERS}
quarkus.http.cors.methods=${CORS_METHODS}
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.access-control-max-age=24h
